### ISSUE TITLE
Recorded video in landscape mode is shown in wrong direction

### ISSUE THREAD

**Issue by jarnoverreyt** [omergul123/LLSimpleCamera#65]
When I record a video in landscape mode, the video is shown in the wrong direction (first image).
It is shown correctly when I record in portrait (second image).

Also I do not have this problem when I capture a picture.

![landscape wrong](https://cloud.githubusercontent.com/assets/1588620/10194801/f3426d38-678a-11e5-8097-7dc05edf72ad.png)
![portrait correct](https://cloud.githubusercontent.com/assets/1588620/10194802/f342e696-678a-11e5-9265-369ceec2bb49.png)

**Comment by yuyedaidao** [comment]
I have the same problem.

**Comment by omergul123** [comment]
@yuyedaidao are you using the latest version 4.1 ?

**Comment by yuyedaidao** [comment]
I will try，thx

**Comment by sonalpaghadal** [comment]
Fixed problem by replacing below lines at line number 245 in file LLSimpleCamera.m
if([self.session canAddInput:_videoDeviceInput]) {
            [self.session  addInput:_videoDeviceInput];
            self.captureVideoPreviewLayer.connection.videoOrientation = AVCaptureVideoOrientationPortrait;
        }

**Comment by yogeshingole** [comment]
Still Getting Same issues.
My requirement is that when record video in Horizontal direction(where App is in portrait mode) , recorded image should be in landscape mode

**Comment by UdaySubbisetty** [comment]
Fixed problem by replacing below lines at line number 802 in file LLSimpleCamera.m

[[UIApplication sharedApplication] statusBarOrientation]
to 
[[UIDevice currentDevice] orientation]

it's working Fine.
